### ISSUE TITLE
LTS 8?

### ISSUE THREAD

**Issue by qrilka** [tolysz/ghcjs-stack#8]
Hello @tolysz 
I think we have discussed about a month ago availability GHCJS for lts-8.x. Unfortunately I coudn't find that discussion. And if I remember it correctly you were saying that it should be ready soon.
Could you give some more current info about it?
Thanks.

**Comment by tolysz** [comment]
Still waiting for new aeson, base and ghcjs-ghc-core support.

**Comment by qrilka** [comment]
@tolysz but wasn't https://github.com/bos/aeson/issues/471 resolved?

**Comment by tolysz** [comment]
Yes it was, but only in: https://github.com/bos/aeson/blob/master/changelog.md#1110

**Comment by qrilka** [comment]
Oh, last LTS uses `aeson-1.0.2.1` - missed that, sorry

**Comment by qrilka** [comment]
Closing in favor of https://github.com/ghcjs/ghcjs-base/issues/93
