### ISSUE TITLE
Is ghcjs.tolysz.org down temporarily?

### ISSUE THREAD

**Issue by Wizek** [tolysz/ghcjs-stack#9]
I've just tried to give reflex-dom a go via stack, and it seems http://ghcjs.tolysz.org/ is down with a 403 HTTP status code.

Is this a good place to ask about this?
Or are you @tolysz perhaps already aware of the issue?

    ➜  reflex-stack git:(master) ✗ stack setup
    Preparing to install GHCJS to an isolated location.
    This will not interfere with any system-level installation.
    Preparing to download ghcjs-0.2.1.9007019_ghc-8.0.1 ...HttpExceptionRequest Request {
      host                 = "ghcjs.tolysz.org"
      port                 = 80
      secure               = False
      requestHeaders       = []
      path                 = "/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz"
      queryString          = ""
      method               = "GET"
      proxy                = Nothing
      rawBody              = False
      redirectCount        = 10
      responseTimeout      = ResponseTimeoutDefault
      requestVersion       = HTTP/1.1
    }
     (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("x-amz-request-id","F3256DE799F5DAA7"),("x-amz-id-2","f6c6Vwmc3NUb67op7jJhDq7jynFl5TKqxQQJFFmkDr/M4adcBFhE+JLbVlxMXvROYpuXoNQiDUc="),("Content-Type","text/html; charset=utf-8"),("Content-Length","338"),("Date","Fri, 23 Jun 2017 16:51:21 GMT"),("Server","AmazonS3")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<html>\n<head><title>403 Forbidden</title></head>\n<body>\n<h1>403 Forbidden</h1>\n<ul>\n<li>Code: AllAccessDisabled</li>\n<li>Message: All access to this object has been disabled</li>\n<li>RequestId: F3256DE799F5DAA7</li>\n<li>HostId: f6c6Vwmc3NUb67op7jJhDq7jynFl5TKqxQQJFFmkDr/M4adcBFhE+JLbVlxMXvROYpuXoNQiDUc=</li>\n</ul>\n<hr/>\n</body>\n</html>\n")

**Comment by tolysz** [comment]
Thanks! It should work again!

**Comment by Wizek** [comment]
Thanks!
